"""create collaboration tables

Revision ID: 0b9a804ef655
Revises: 3601820a96d4
Create Date: 2026-06-30 20:53:23.428409

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9a804ef655'
down_revision: Union[str, Sequence[str], None] = '3601820a96d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_created_by'), 'collaborations', ['created_by'], unique=False)
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.create_table('collaboration_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collaboration_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_memberships_collaboration_id'), 'collaboration_memberships', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collaboration_memberships_user_id'), 'collaboration_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaboration_memberships_user_id'), table_name='collaboration_memberships')
    op.drop_index(op.f('ix_collaboration_memberships_collaboration_id'), table_name='collaboration_memberships')
    op.drop_table('collaboration_memberships')
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_created_by'), table_name='collaborations')
    op.drop_table('collaborations')
    # ### end Alembic commands ###
