"""add collaboration join requests

Revision ID: 4c2836b7ce49
Revises: fa5d7d8de0f5
Create Date: 2026-07-01 22:15:38.658800

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2836b7ce49'
down_revision: Union[str, Sequence[str], None] = 'fa5d7d8de0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration_join_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collaboration_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_join_requests_collaboration_id'), 'collaboration_join_requests', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collaboration_join_requests_user_id'), 'collaboration_join_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaboration_join_requests_user_id'), table_name='collaboration_join_requests')
    op.drop_index(op.f('ix_collaboration_join_requests_collaboration_id'), table_name='collaboration_join_requests')
    op.drop_table('collaboration_join_requests')
    # ### end Alembic commands ###
