"""add cascade delete to collaboration memberships

Revision ID: 5d6ddbad0703
Revises: 4c2836b7ce49
Create Date: 2026-07-05 15:26:19.475401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6ddbad0703'
down_revision: Union[str, Sequence[str], None] = '4c2836b7ce49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collaboration_memberships_collaboration_id_fkey'), 'collaboration_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'collaboration_memberships', 'collaborations', ['collaboration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_collaborations_created_by'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.create_index(op.f('ix_collaborations_created_by'), 'collaborations', ['created_by'], unique=False)
    op.drop_constraint(None, 'collaboration_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('collaboration_memberships_collaboration_id_fkey'), 'collaboration_memberships', 'collaborations', ['collaboration_id'], ['id'])
    # ### end Alembic commands ###
