"""add submission indexes

Revision ID: 900293e1a0df
Revises: 770cd1cdc25b
Create Date: 2026-06-29 21:27:10.601817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900293e1a0df'
down_revision: Union[str, Sequence[str], None] = '770cd1cdc25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submissions_challenge_id'), 'submissions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_challenge_id'), table_name='submissions')
    # ### end Alembic commands ###
