"""rename challenge_resource_requests to resource_requests

Revision ID: 9eda9a5013c7
Revises: b2f4c9d7a111
Create Date: 2026-08-07 09:30:08.842306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9eda9a5013c7'
down_revision: Union[str, Sequence[str], None] = 'b2f4c9d7a111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=True),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['coding_challenges.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_requests_challenge_id'), 'resource_requests', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_resource_requests_requester_id'), 'resource_requests', ['requester_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=True),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['coding_challenges.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_challenge_id'), 'resources', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_resources_uploader_id'), 'resources', ['uploader_id'], unique=False)
    op.drop_index(op.f('ix_challenge_resources_challenge_id'), table_name='challenge_resources')
    op.drop_index(op.f('ix_challenge_resources_uploader_id'), table_name='challenge_resources')
    op.drop_table('challenge_resources')
    op.drop_index(op.f('ix_challenge_resource_requests_challenge_id'), table_name='challenge_resource_requests')
    op.drop_index(op.f('ix_challenge_resource_requests_requester_id'), table_name='challenge_resource_requests')
    op.drop_table('challenge_resource_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_resource_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['coding_challenges.id'], name=op.f('challenge_resource_requests_challenge_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.uid'], name=op.f('challenge_resource_requests_requester_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('challenge_resource_requests_pkey'))
    )
    op.create_index(op.f('ix_challenge_resource_requests_requester_id'), 'challenge_resource_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_challenge_resource_requests_challenge_id'), 'challenge_resource_requests', ['challenge_id'], unique=False)
    op.create_table('challenge_resources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['coding_challenges.id'], name=op.f('challenge_resources_challenge_id_fkey')),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.uid'], name=op.f('challenge_resources_uploader_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('challenge_resources_pkey'))
    )
    op.create_index(op.f('ix_challenge_resources_uploader_id'), 'challenge_resources', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_challenge_resources_challenge_id'), 'challenge_resources', ['challenge_id'], unique=False)
    op.drop_index(op.f('ix_resources_uploader_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_challenge_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_resource_requests_requester_id'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_challenge_id'), table_name='resource_requests')
    op.drop_table('resource_requests')
    # ### end Alembic commands ###
