"""add cascade delete to collaboration join requests

Revision ID: bb97d88dd536
Revises: 9eda9a5013c7
Create Date: 2026-08-08 06:50:17.320422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb97d88dd536'
down_revision: Union[str, Sequence[str], None] = '9eda9a5013c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collaboration_join_requests_collaboration_id_fkey'), 'collaboration_join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'collaboration_join_requests', 'collaborations', ['collaboration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collaboration_join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('collaboration_join_requests_collaboration_id_fkey'), 'collaboration_join_requests', 'collaborations', ['collaboration_id'], ['id'])
    # ### end Alembic commands ###
