/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollaborationsIndexRouteImport } from './routes/collaborations.index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CollaborationsNewRouteImport } from './routes/collaborations.new'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges.$challengeId'
import { Route as CollaborationsCollaborationIdIndexRouteImport } from './routes/collaborations.$collaborationId.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin.submissions.index'
import { Route as AdminCollaborationsIndexRouteImport } from './routes/admin.collaborations.index'
import { Route as AdminChallengesIndexRouteImport } from './routes/admin.challenges.index'
import { Route as CollaborationsCollaborationIdRequestsRouteImport } from './routes/collaborations.$collaborationId.requests'
import { Route as CollaborationsCollaborationIdMembersRouteImport } from './routes/collaborations.$collaborationId.members'
import { Route as CollaborationsCollaborationIdEditRouteImport } from './routes/collaborations.$collaborationId.edit'
import { Route as AdminChallengesNewRouteImport } from './routes/admin.challenges.new'
import { Route as AdminUsersUserIdSubmissionsRouteImport } from './routes/admin.users.$userId.submissions'
import { Route as AdminChallengesChallengeIdEditRouteImport } from './routes/admin.challenges.$challengeId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsIndexRoute = CollaborationsIndexRouteImport.update({
  id: '/collaborations/',
  path: '/collaborations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsNewRoute = CollaborationsNewRouteImport.update({
  id: '/collaborations/new',
  path: '/collaborations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/challenges/$challengeId',
  path: '/challenges/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsCollaborationIdIndexRoute =
  CollaborationsCollaborationIdIndexRouteImport.update({
    id: '/collaborations/$collaborationId/',
    path: '/collaborations/$collaborationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/admin/submissions/',
  path: '/admin/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaborationsIndexRoute =
  AdminCollaborationsIndexRouteImport.update({
    id: '/admin/collaborations/',
    path: '/admin/collaborations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChallengesIndexRoute = AdminChallengesIndexRouteImport.update({
  id: '/admin/challenges/',
  path: '/admin/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsCollaborationIdRequestsRoute =
  CollaborationsCollaborationIdRequestsRouteImport.update({
    id: '/collaborations/$collaborationId/requests',
    path: '/collaborations/$collaborationId/requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollaborationsCollaborationIdMembersRoute =
  CollaborationsCollaborationIdMembersRouteImport.update({
    id: '/collaborations/$collaborationId/members',
    path: '/collaborations/$collaborationId/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollaborationsCollaborationIdEditRoute =
  CollaborationsCollaborationIdEditRouteImport.update({
    id: '/collaborations/$collaborationId/edit',
    path: '/collaborations/$collaborationId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChallengesNewRoute = AdminChallengesNewRouteImport.update({
  id: '/admin/challenges/new',
  path: '/admin/challenges/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdSubmissionsRoute =
  AdminUsersUserIdSubmissionsRouteImport.update({
    id: '/admin/users/$userId/submissions',
    path: '/admin/users/$userId/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChallengesChallengeIdEditRoute =
  AdminChallengesChallengeIdEditRouteImport.update({
    id: '/admin/challenges/$challengeId/edit',
    path: '/admin/challenges/$challengeId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/collaborations/new': typeof CollaborationsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/admin/challenges/new': typeof AdminChallengesNewRoute
  '/collaborations/$collaborationId/edit': typeof CollaborationsCollaborationIdEditRoute
  '/collaborations/$collaborationId/members': typeof CollaborationsCollaborationIdMembersRoute
  '/collaborations/$collaborationId/requests': typeof CollaborationsCollaborationIdRequestsRoute
  '/admin/challenges/': typeof AdminChallengesIndexRoute
  '/admin/collaborations/': typeof AdminCollaborationsIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/collaborations/$collaborationId/': typeof CollaborationsCollaborationIdIndexRoute
  '/admin/challenges/$challengeId/edit': typeof AdminChallengesChallengeIdEditRoute
  '/admin/users/$userId/submissions': typeof AdminUsersUserIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/collaborations/new': typeof CollaborationsNewRoute
  '/admin': typeof AdminIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/collaborations': typeof CollaborationsIndexRoute
  '/admin/challenges/new': typeof AdminChallengesNewRoute
  '/collaborations/$collaborationId/edit': typeof CollaborationsCollaborationIdEditRoute
  '/collaborations/$collaborationId/members': typeof CollaborationsCollaborationIdMembersRoute
  '/collaborations/$collaborationId/requests': typeof CollaborationsCollaborationIdRequestsRoute
  '/admin/challenges': typeof AdminChallengesIndexRoute
  '/admin/collaborations': typeof AdminCollaborationsIndexRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/collaborations/$collaborationId': typeof CollaborationsCollaborationIdIndexRoute
  '/admin/challenges/$challengeId/edit': typeof AdminChallengesChallengeIdEditRoute
  '/admin/users/$userId/submissions': typeof AdminUsersUserIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/collaborations/new': typeof CollaborationsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/admin/challenges/new': typeof AdminChallengesNewRoute
  '/collaborations/$collaborationId/edit': typeof CollaborationsCollaborationIdEditRoute
  '/collaborations/$collaborationId/members': typeof CollaborationsCollaborationIdMembersRoute
  '/collaborations/$collaborationId/requests': typeof CollaborationsCollaborationIdRequestsRoute
  '/admin/challenges/': typeof AdminChallengesIndexRoute
  '/admin/collaborations/': typeof AdminCollaborationsIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/collaborations/$collaborationId/': typeof CollaborationsCollaborationIdIndexRoute
  '/admin/challenges/$challengeId/edit': typeof AdminChallengesChallengeIdEditRoute
  '/admin/users/$userId/submissions': typeof AdminUsersUserIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/my-submissions'
    | '/profile'
    | '/signup'
    | '/challenges/$challengeId'
    | '/collaborations/new'
    | '/admin/'
    | '/challenges/'
    | '/collaborations/'
    | '/admin/challenges/new'
    | '/collaborations/$collaborationId/edit'
    | '/collaborations/$collaborationId/members'
    | '/collaborations/$collaborationId/requests'
    | '/admin/challenges/'
    | '/admin/collaborations/'
    | '/admin/submissions/'
    | '/admin/users/'
    | '/collaborations/$collaborationId/'
    | '/admin/challenges/$challengeId/edit'
    | '/admin/users/$userId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/my-submissions'
    | '/profile'
    | '/signup'
    | '/challenges/$challengeId'
    | '/collaborations/new'
    | '/admin'
    | '/challenges'
    | '/collaborations'
    | '/admin/challenges/new'
    | '/collaborations/$collaborationId/edit'
    | '/collaborations/$collaborationId/members'
    | '/collaborations/$collaborationId/requests'
    | '/admin/challenges'
    | '/admin/collaborations'
    | '/admin/submissions'
    | '/admin/users'
    | '/collaborations/$collaborationId'
    | '/admin/challenges/$challengeId/edit'
    | '/admin/users/$userId/submissions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/my-submissions'
    | '/profile'
    | '/signup'
    | '/challenges/$challengeId'
    | '/collaborations/new'
    | '/admin/'
    | '/challenges/'
    | '/collaborations/'
    | '/admin/challenges/new'
    | '/collaborations/$collaborationId/edit'
    | '/collaborations/$collaborationId/members'
    | '/collaborations/$collaborationId/requests'
    | '/admin/challenges/'
    | '/admin/collaborations/'
    | '/admin/submissions/'
    | '/admin/users/'
    | '/collaborations/$collaborationId/'
    | '/admin/challenges/$challengeId/edit'
    | '/admin/users/$userId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
  CollaborationsNewRoute: typeof CollaborationsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CollaborationsIndexRoute: typeof CollaborationsIndexRoute
  AdminChallengesNewRoute: typeof AdminChallengesNewRoute
  CollaborationsCollaborationIdEditRoute: typeof CollaborationsCollaborationIdEditRoute
  CollaborationsCollaborationIdMembersRoute: typeof CollaborationsCollaborationIdMembersRoute
  CollaborationsCollaborationIdRequestsRoute: typeof CollaborationsCollaborationIdRequestsRoute
  AdminChallengesIndexRoute: typeof AdminChallengesIndexRoute
  AdminCollaborationsIndexRoute: typeof AdminCollaborationsIndexRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  CollaborationsCollaborationIdIndexRoute: typeof CollaborationsCollaborationIdIndexRoute
  AdminChallengesChallengeIdEditRoute: typeof AdminChallengesChallengeIdEditRoute
  AdminUsersUserIdSubmissionsRoute: typeof AdminUsersUserIdSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/': {
      id: '/collaborations/'
      path: '/collaborations'
      fullPath: '/collaborations/'
      preLoaderRoute: typeof CollaborationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/new': {
      id: '/collaborations/new'
      path: '/collaborations/new'
      fullPath: '/collaborations/new'
      preLoaderRoute: typeof CollaborationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$challengeId': {
      id: '/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collaborationId/': {
      id: '/collaborations/$collaborationId/'
      path: '/collaborations/$collaborationId'
      fullPath: '/collaborations/$collaborationId/'
      preLoaderRoute: typeof CollaborationsCollaborationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/admin/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaborations/': {
      id: '/admin/collaborations/'
      path: '/admin/collaborations'
      fullPath: '/admin/collaborations/'
      preLoaderRoute: typeof AdminCollaborationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/challenges/': {
      id: '/admin/challenges/'
      path: '/admin/challenges'
      fullPath: '/admin/challenges/'
      preLoaderRoute: typeof AdminChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collaborationId/requests': {
      id: '/collaborations/$collaborationId/requests'
      path: '/collaborations/$collaborationId/requests'
      fullPath: '/collaborations/$collaborationId/requests'
      preLoaderRoute: typeof CollaborationsCollaborationIdRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collaborationId/members': {
      id: '/collaborations/$collaborationId/members'
      path: '/collaborations/$collaborationId/members'
      fullPath: '/collaborations/$collaborationId/members'
      preLoaderRoute: typeof CollaborationsCollaborationIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collaborationId/edit': {
      id: '/collaborations/$collaborationId/edit'
      path: '/collaborations/$collaborationId/edit'
      fullPath: '/collaborations/$collaborationId/edit'
      preLoaderRoute: typeof CollaborationsCollaborationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/challenges/new': {
      id: '/admin/challenges/new'
      path: '/admin/challenges/new'
      fullPath: '/admin/challenges/new'
      preLoaderRoute: typeof AdminChallengesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/submissions': {
      id: '/admin/users/$userId/submissions'
      path: '/admin/users/$userId/submissions'
      fullPath: '/admin/users/$userId/submissions'
      preLoaderRoute: typeof AdminUsersUserIdSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/challenges/$challengeId/edit': {
      id: '/admin/challenges/$challengeId/edit'
      path: '/admin/challenges/$challengeId/edit'
      fullPath: '/admin/challenges/$challengeId/edit'
      preLoaderRoute: typeof AdminChallengesChallengeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MySubmissionsRoute: MySubmissionsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
  CollaborationsNewRoute: CollaborationsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CollaborationsIndexRoute: CollaborationsIndexRoute,
  AdminChallengesNewRoute: AdminChallengesNewRoute,
  CollaborationsCollaborationIdEditRoute:
    CollaborationsCollaborationIdEditRoute,
  CollaborationsCollaborationIdMembersRoute:
    CollaborationsCollaborationIdMembersRoute,
  CollaborationsCollaborationIdRequestsRoute:
    CollaborationsCollaborationIdRequestsRoute,
  AdminChallengesIndexRoute: AdminChallengesIndexRoute,
  AdminCollaborationsIndexRoute: AdminCollaborationsIndexRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  CollaborationsCollaborationIdIndexRoute:
    CollaborationsCollaborationIdIndexRoute,
  AdminChallengesChallengeIdEditRoute: AdminChallengesChallengeIdEditRoute,
  AdminUsersUserIdSubmissionsRoute: AdminUsersUserIdSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
