/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as MySubmissionsRouteImport } from './routes/my-submissions';
import { Route as LoginRouteImport } from './routes/login';
import { Route as LeaderboardRouteImport } from './routes/leaderboard';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CollaborationsIndexRouteImport } from './routes/collaborations.index';
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as CollaborationsNewRouteImport } from './routes/collaborations.new';
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges.$challengeId';
import { Route as CollaborationsCollaborationIdIndexRouteImport } from './routes/collaborations.$collaborationId.index';
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index';
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin.submissions.index';
import { Route as AdminCollaborationsIndexRouteImport } from './routes/admin.collaborations.index';
import { Route as AdminChallengesIndexRouteImport } from './routes/admin.challenges.index';
import { Route as CollaborationsCollaborationIdRequestsRouteImport } from './routes/collaborations.$collaborationId.requests';
import { Route as CollaborationsCollaborationIdMembersRouteImport } from './routes/collaborations.$collaborationId.members';
import { Route as CollaborationsCollaborationIdEditRouteImport } from './routes/collaborations.$collaborationId.edit';
import { Route as AdminChallengesNewRouteImport } from './routes/admin.challenges.new';
import { Route as AdminUsersUserIdSubmissionsRouteImport } from './routes/admin.users.$userId.submissions';
import { Route as AdminChallengesChallengeIdEditRouteImport } from './routes/admin.challenges.$challengeId.edit';
const SignupRoute = SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const MySubmissionsRoute = MySubmissionsRouteImport.update({
    id: '/my-submissions',
    path: '/my-submissions',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const LeaderboardRoute = LeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsIndexRoute = CollaborationsIndexRouteImport.update({
    id: '/collaborations/',
    path: '/collaborations/',
    getParentRoute: () => rootRouteImport,
});
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsNewRoute = CollaborationsNewRouteImport.update({
    id: '/collaborations/new',
    path: '/collaborations/new',
    getParentRoute: () => rootRouteImport,
});
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
    id: '/challenges/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsCollaborationIdIndexRoute = CollaborationsCollaborationIdIndexRouteImport.update({
    id: '/collaborations/$collaborationId/',
    path: '/collaborations/$collaborationId/',
    getParentRoute: () => rootRouteImport,
});
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => rootRouteImport,
});
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
    id: '/admin/submissions/',
    path: '/admin/submissions/',
    getParentRoute: () => rootRouteImport,
});
const AdminCollaborationsIndexRoute = AdminCollaborationsIndexRouteImport.update({
    id: '/admin/collaborations/',
    path: '/admin/collaborations/',
    getParentRoute: () => rootRouteImport,
});
const AdminChallengesIndexRoute = AdminChallengesIndexRouteImport.update({
    id: '/admin/challenges/',
    path: '/admin/challenges/',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsCollaborationIdRequestsRoute = CollaborationsCollaborationIdRequestsRouteImport.update({
    id: '/collaborations/$collaborationId/requests',
    path: '/collaborations/$collaborationId/requests',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsCollaborationIdMembersRoute = CollaborationsCollaborationIdMembersRouteImport.update({
    id: '/collaborations/$collaborationId/members',
    path: '/collaborations/$collaborationId/members',
    getParentRoute: () => rootRouteImport,
});
const CollaborationsCollaborationIdEditRoute = CollaborationsCollaborationIdEditRouteImport.update({
    id: '/collaborations/$collaborationId/edit',
    path: '/collaborations/$collaborationId/edit',
    getParentRoute: () => rootRouteImport,
});
const AdminChallengesNewRoute = AdminChallengesNewRouteImport.update({
    id: '/admin/challenges/new',
    path: '/admin/challenges/new',
    getParentRoute: () => rootRouteImport,
});
const AdminUsersUserIdSubmissionsRoute = AdminUsersUserIdSubmissionsRouteImport.update({
    id: '/admin/users/$userId/submissions',
    path: '/admin/users/$userId/submissions',
    getParentRoute: () => rootRouteImport,
});
const AdminChallengesChallengeIdEditRoute = AdminChallengesChallengeIdEditRouteImport.update({
    id: '/admin/challenges/$challengeId/edit',
    path: '/admin/challenges/$challengeId/edit',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    DashboardRoute: DashboardRoute,
    LeaderboardRoute: LeaderboardRoute,
    LoginRoute: LoginRoute,
    MySubmissionsRoute: MySubmissionsRoute,
    ProfileRoute: ProfileRoute,
    SignupRoute: SignupRoute,
    ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
    CollaborationsNewRoute: CollaborationsNewRoute,
    AdminIndexRoute: AdminIndexRoute,
    ChallengesIndexRoute: ChallengesIndexRoute,
    CollaborationsIndexRoute: CollaborationsIndexRoute,
    AdminChallengesNewRoute: AdminChallengesNewRoute,
    CollaborationsCollaborationIdEditRoute: CollaborationsCollaborationIdEditRoute,
    CollaborationsCollaborationIdMembersRoute: CollaborationsCollaborationIdMembersRoute,
    CollaborationsCollaborationIdRequestsRoute: CollaborationsCollaborationIdRequestsRoute,
    AdminChallengesIndexRoute: AdminChallengesIndexRoute,
    AdminCollaborationsIndexRoute: AdminCollaborationsIndexRoute,
    AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
    AdminUsersIndexRoute: AdminUsersIndexRoute,
    CollaborationsCollaborationIdIndexRoute: CollaborationsCollaborationIdIndexRoute,
    AdminChallengesChallengeIdEditRoute: AdminChallengesChallengeIdEditRoute,
    AdminUsersUserIdSubmissionsRoute: AdminUsersUserIdSubmissionsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
